# Generated by Django 4.2.11 on 2024-03-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('transportation_mode', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('metro', 'Metro'), ('walk', 'Walk')], max_length=20)),
                ('extra_prep_time', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
    ]
